root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/arandu ./cmd/server"
  entrypoint = "./tmp/arandu"
  include_ext = ["go", "mod", "sum"]
  exclude_dir = ["frontend", "tmp", "bin", "data", "dist", "web"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true
